- hosts: web
  become: true

  vars:
    aws_region: ap-southeast-1
    app_name: my-devops-project

  tasks:
    - name: Login to ECR
      shell: |
        aws ecr get-login-password --region {{ aws_region }} \
        | docker login --username AWS --password-stdin {{ lookup('env','ACCOUNT_ID') }}.dkr.ecr.{{ aws_region }}.amazonaws.com
      args:
        executable: /bin/bash

    - name: Pull image
      docker_container:
        name: webapp
        image: "{{ lookup('env','ACCOUNT_ID') }}.dkr.ecr.{{ aws_region }}.amazonaws.com/{{ app_name }}:latest"
        state: started
        restart_policy: always
        ports:
          - "80:80"
