---
- name: Run Grafana in Docker
  hosts: monitoring
  become: true

  vars:
    aws_region: ap-southeast-1
    account_id: "{{ lookup('env','ACCOUNT_ID') }}"

  tasks:
    - name: Create Grafana data dir
      file:
        path: /opt/grafana
        state: directory
        owner: 472
        group: 472

    - name: Login to ECR
      shell: |
        aws ecr get-login-password --region {{ aws_region }} \
        | docker login \
          --username AWS \
          --password-stdin \
          {{ account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com

    - name: Run Grafana container
      community.docker.docker_container:
        name: grafana
        image: "{{ account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/monitoring/grafana:latest"
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
        volumes:
          - /opt/grafana:/var/lib/grafana
