---
- name: Install Grafana
  hosts: monitoring
  become: true
  collections:
    - grafana.grafana
  roles:
    - grafana
  vars:
    grafana_ini:
      security:
        admin_user: "admin"
        admin_password: "admin"
