---
- name: Run Node Exporter in Docker
  hosts: web
  become: true

  vars:
    aws_region: ap-southeast-1
    ecr_repo: monitoring/node-exporter

  tasks:
    - name: Get AWS account ID
      command: aws sts get-caller-identity --query Account --output text
      register: aws_account_id
      changed_when: false

    - name: Fail if AWS account ID missing
      fail:
        msg: "AWS account ID is empty â€” check EC2 IAM role"
      when: aws_account_id.stdout | length == 0

    - name: Login to ECR
      shell: |
        aws ecr get-login-password --region {{ aws_region }} \
        | docker login \
          --username AWS \
          --password-stdin \
          {{ aws_account_id.stdout }}.dkr.ecr.{{ aws_region }}.amazonaws.com

    - name: Remove existing node-exporter container
      community.docker.docker_container:
        name: node-exporter
        state: absent

    - name: Run node-exporter container
      community.docker.docker_container:
        name: node-exporter
        image: "{{ aws_account_id.stdout }}.dkr.ecr.{{ aws_region }}.amazonaws.com/{{ ecr_repo }}:latest"
        state: started
        restart_policy: always
        network_mode: host
        pull: true
        recreate: true
