- name: Install Prometheus on monitoring server
  hosts: monitoring
  become: true

  vars:
    prometheus_scrape_configs:
      - job_name: "node_exporter"
        static_configs:
          - targets:
              - "{{ hostvars['web'].ansible_host }}:9100"

  roles:
    - prometheus.prometheus.prometheus
